# 公共配置文件
spring:
  application:
    name: CXOJ-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 邮件
  mail:
    host: smtp.qq.com # qq邮箱
    username: 3773112670@qq.com
    password: nrvtmbewufhycfje  # qq授权码
    port: 25
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  address: 0.0.0.0
  port: 8011
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  mp:
    # 前端绑定url
    bindUrl: http://vm92zr14234.vicp.fun/user/login
    # 后端回调url
    url: http://vm92zr14234.vicp.fun:21299/api/weChat/mp/callback
    token: xxx
    aesKey: xxx
    appId: wx2b5726143f1d3089 #  wx3e40bf8e5e3ec055
    secret: 1a6b7eb07a9cdf887b43f74c634a8564 #  977160cf417d800e2ecafccc7e14dd39
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  open:
    appId: wx2b5726143f1d3089
    appSecret: 1a6b7eb07a9cdf887b43f74c634a8564
  # 微信小程序
  miniapp:
    appid: wx56450d1cf83e4932 # 小程序微信公众平台appId
    secret: fe6fb7cfdd78ba3a2d948c5d62c704e2  # 小程序微信公众平台api秘钥
    msgDataFormat: JSON
# 对象存储
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yp.CXOJ.controller
#代码沙箱配置
codeSandBox:
  type: example

# 七 牛 云配置
oss:
  accessKey: 3I29nKtZ6RJs7h97YTwRlnjqT2ypz-L0PxiI-u_R
  secretKey: hcU5zOpdA5TQBf2p5eo_bOf_GZVUqZPk3QgtFQiz
  bucket: cxoj
  url: http://sf23aw742.hn-bkt.clouddn.com/